### ISSUE TITLE
Excited when I saw this, but the tests come back as failures

### ISSUE THREAD

**Issue by sshadmand** [PyrApple/node-audio-slicer#1]
Anyone able to get this repo back in shape. Buy you a beer!
```
$ yarn test
yarn run v1.6.0
$ ./node_modules/.bin/mocha


  Reader
TypeError: callback is not a function
    at Reader.loadBuffer (/Users/seanshadmand/Downloads/slicer/dist/Slicer.js:215:9)
    at Context.assertions (/Users/seanshadmand/Downloads/slicer/test/tests.js:28:19)
    at callFn (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:443:10)
    at /Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:361:14)
    at /Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
    1) Read .wav file

  Slicer
    Slice .wav file to mp3
      2) should slice wav into mp3 chunks
    Slice .wav file to wav
      3) should slice wav into wav chunks
    Slice 4ch .wav + auto detect
{ Error: ENOENT: no such file or directory, open './test/example4ch.wav'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Reader.loadBuffer (/Users/seanshadmand/Downloads/slicer/dist/Slicer.js:214:25)
    at Slicer.slice (/Users/seanshadmand/Downloads/slicer/dist/Slicer.js:43:19)
    at Context.it (/Users/seanshadmand/Downloads/slicer/test/tests.js:75:14)
    at callFnAsync (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:443:10)
    at /Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:361:14)
    at /Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/seanshadmand/Downloads/slicer/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './test/example4ch.wav' }
      4) should slice wav into wav chunks


  0 passing (6s)
  4 failing

  1) Reader Read .wav file:
     TypeError: Cannot read property 'then' of undefined
      at Context.assertions (test/tests.js:29:7)

  2) Slicer Slice .wav file to mp3 should slice wav into mp3 chunks:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) Slicer Slice .wav file to wav should slice wav into wav chunks:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  4) Slicer Slice 4ch .wav + auto detect should slice wav into wav chunks:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by PyrApple** [comment]
Fixed the test file, I'll let you know when I'm flying around the US for the bear :)
